package gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manejador_xml.ManejadorDOM;
import manejador_xml.ManejadorSAX;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;

/**
 *
 * @author Alumno
 */
public class GUI extends javax.swing.JFrame {

    public String manejadorXML;
    public String nombreFichero;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfMostrarXML = new javax.swing.JFrame();
        aceptarButton2 = new javax.swing.JButton();
        cancelarButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatosXML = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        aceptarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        tipoFicheroLablel = new javax.swing.JLabel();
        extensionComboBox = new javax.swing.JComboBox<>();
        nombreDelFicheroLabel = new javax.swing.JLabel();
        nombreDelFicheroField = new javax.swing.JTextField();

        aceptarButton2.setText("Volver");
        aceptarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButton2ActionPerformed(evt);
            }
        });

        cancelarButton2.setText("Cerrar aplicación");
        cancelarButton2.setActionCommand("Salir");
        cancelarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton2ActionPerformed(evt);
            }
        });

        jtaDatosXML.setColumns(20);
        jtaDatosXML.setRows(5);
        jScrollPane1.setViewportView(jtaDatosXML);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Datos del XML");

        javax.swing.GroupLayout jfMostrarXMLLayout = new javax.swing.GroupLayout(jfMostrarXML.getContentPane());
        jfMostrarXML.getContentPane().setLayout(jfMostrarXMLLayout);
        jfMostrarXMLLayout.setHorizontalGroup(
            jfMostrarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfMostrarXMLLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jfMostrarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfMostrarXMLLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cancelarButton2)
                        .addGap(39, 39, 39)
                        .addComponent(aceptarButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jfMostrarXMLLayout.setVerticalGroup(
            jfMostrarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfMostrarXMLLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jfMostrarXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton2)
                    .addComponent(cancelarButton2))
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButton(evt);
            }
        });

        tipoFicheroLablel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipoFicheroLablel.setText("Como leer XML");

        extensionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAX", "DOM" }));
        extensionComboBox.setToolTipText("");

        nombreDelFicheroLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreDelFicheroLabel.setText("Nombre del fichero");

        nombreDelFicheroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDelFicheroFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreDelFicheroLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aceptarButton))
                        .addComponent(nombreDelFicheroField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tipoFicheroLablel)
                            .addGap(18, 18, 18)
                            .addComponent(extensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nombreDelFicheroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreDelFicheroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoFicheroLablel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton)
                    .addComponent(cancelarButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton
        //Cerramos la aplicación
        System.exit(0);
    }//GEN-LAST:event_cancelarButton

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        //Input del fichero
        nombreFichero = this.nombreDelFicheroField.getText();

        //Si el input del fichero no esta vacio
        if (!nombreFichero.isEmpty()) {

            String datosXML = "";

            //Desplegable que nos devuelve "SAX" o "DOM"
            manejadorXML = this.extensionComboBox.getSelectedItem().toString();

            //Si usuario selecciona DOM
            if (manejadorXML.equals("DOM")) {
                //Creamos file 
                File file = new File(nombreFichero);

                //Instanciamos la clase que maneja DOM
                ManejadorDOM dom = new ManejadorDOM(file);

                //Nos devuelve todo los datos del XML
                datosXML = dom.recorrerYMostrar();

                //Abrimos JFrame que muestra el XML 
                this.jfMostrarXML.setVisible(true);
                this.jfMostrarXML.setSize(450, 350);

                //Si usuario selecciona SAX
            } else {
                try {
                    //Instanciamos la clase que maneja SAX
                    ManejadorSAX sax = new ManejadorSAX();

                    // Creamos la factoria de parseadores por defecto  
                    XMLReader reader = XMLReaderFactory.createXMLReader();

                    // Añadimos nuestro manejador al reader  
                    reader.setContentHandler(new ManejadorSAX());

                    // Procesamos el xml de ejemplo  
                    reader.parse(new InputSource(new FileInputStream("./" + nombreFichero)));

                    //Nos devuelve todos los datos del XML
                    datosXML = ManejadorSAX.datosXML;

                    //Abrimos JFrame que muestra el XML 
                    this.jfMostrarXML.setVisible(true);
                    this.jfMostrarXML.setSize(450, 350);

                } catch (SAXException e) {
                    JOptionPane.showMessageDialog(null, "Error de formato en el XML", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Error al abrir el fichero", "Error", JOptionPane.ERROR_MESSAGE);

                }
            }
            /*
                //Nos devuelve todos los datos del XML
                datosXML = sax.getDatosXML();

                System.out.println("datosXML" + datosXML);
            }
             */
            //Mostramos por pantalla los datos obtenido del XML
            this.jtaDatosXML.setText(datosXML);

            //Si el input del fichero es vacio
        } else {
            //Mensaje de error inputText.length==0
            JOptionPane.showMessageDialog(null, "Debes introducir el nombre del fichero a leer", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void aceptarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButton2ActionPerformed
        //Hacemos inivisible el jFrame que muestra los datos XML
        this.jfMostrarXML.setVisible(false);

        //Hacemos visible el JFrame inicial 
        this.setVisible(true);
    }//GEN-LAST:event_aceptarButton2ActionPerformed

    private void cancelarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButton2ActionPerformed
        //Cerramos la aplicación
        System.exit(0);
    }//GEN-LAST:event_cancelarButton2ActionPerformed

    private void nombreDelFicheroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDelFicheroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreDelFicheroFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton aceptarButton2;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton cancelarButton2;
    private javax.swing.JComboBox<String> extensionComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame jfMostrarXML;
    private javax.swing.JTextArea jtaDatosXML;
    private javax.swing.JTextField nombreDelFicheroField;
    private javax.swing.JLabel nombreDelFicheroLabel;
    private javax.swing.JLabel tipoFicheroLablel;
    // End of variables declaration//GEN-END:variables
}
